Descriptive Statistics - Measures of Central Tendency and
variability
Perform the following operations on any open source dataset
(e.g., data.csv)
1. Provide summary statistics (mean, median, minimum,
maximum, standard deviation) for a dataset (age, income etc.)
with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical
variable is age groups and quantitative variable is income, then
provide summary statistics of income grouped by the age
groups. Create a list that contains a numeric value for each
response to the categorical variable.
2. Write a Python program to display some basic statistical
details like percentile, mean, standard deviation etc. of the
species of 'Iris-setosa' , 'Iris-versicolor', and 'Iris-virginica' of
iris.csv dataset.
Provide the codes with outputs and explain everything that you
do in this step.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/student_data.csv")

In [ ]:
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

In [ ]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [ ]:
df.groupby("age").describe()

      Medu                                                Fedu            ...  \
     count      mean       std  min  25%  50%  75%  max  count      mean  ...
age                                                                       ...
15    82.0  3.036585  1.059293  1.0  2.0  3.0  4.0  4.0   82.0  2.756098  ...
16   104.0  2.826923  1.037569  0.0  2.0  3.0  4.0  4.0  104.0  2.576923  ...
17    98.0  2.612245  1.099509  0.0  2.0  3.0  4.0  4.0   98.0  2.469388  ...
18    82.0  2.707317  1.105405  1.0  2.0  3.0  4.0  4.0   82.0  2.475610  ...
19    24.0  2.166667  1.167184  0.0  1.0  2.0  3.0  4.0   24.0  2.041667  ...
20     3.0  3.000000  1.000000  2.0  2.5  3.0  3.5  4.0    3.0  2.000000  ...
21     1.0  1.000000       NaN  1.0  1.0  1.0  1.0  1.0    1.0  1.000000  ...
22     1.0  3.000000       NaN  3.0  3.0  3.0  3.0  3.0    1.0  1.000000  ...

        G2           G3
       75%   max  count       mean       std  min    25%   50%   75%   max
age
15   14.00  19.0   82.0  11.256098  4.596861  0.0   9.25  11.0  15.0  19.0
16   14.00  19.0  104.0  11.028846  4.282402  0.0   9.00  11.0  14.0  20.0
17   12.75  18.0   98.0  10.275510  4.290437  0.0   9.00  11.0  13.0  18.0
18   13.00  18.0   82.0   9.548780  4.994200  0.0   8.00  10.0  13.0  19.0
19   11.25  14.0   24.0   8.208333  4.606037  0.0   8.00   9.0  11.0  13.0
20   16.00  18.0    3.0  14.000000  4.582576  9.0  12.00  15.0  16.5  18.0
21    8.00   8.0    1.0   7.000000       NaN  7.0   7.00   7.0   7.0   7.0
22    8.00   8.0    1.0   8.000000       NaN  8.0   8.00   8.0   8.0   8.0

[8 rows x 120 columns]